configuration: 
  - Release

pull_requests:
  do_not_increment_build_number: true

install:
  - cinst gitversion.portable -pre -y
  - cinst gitlink -Pre -y
  - if not exist gtk-sharp-2.12.26.msi appveyor DownloadFile http://download.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.26.msi
  - msiexec /i gtk-sharp-2.12.26.msi /qn /norestart
  - if not exist gtk-sharp-2.99.3.msi appveyor DownloadFile https://download.gnome.org/binaries/win32/gtk-sharp/2.99/gtk-sharp-2.99.3.msi
  - msiexec /i gtk-sharp-2.99.3.msi /qn /norestart

cache:
  - gtk-sharp-2.12.26.msi
  - gtk-sharp-2.99.3.msi

before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - git submodule update --init --recursive
  - NuGet restore Source/OxyPlot.AppVeyor.sln
  - gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
  - msbuild Source/OxyPlot.AppVeyor.sln "/property:Platform=Any CPU" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
#  - msbuild Source/OxyPlot.AppVeyor.sln /property:Platform=x86 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
#  - msbuild Source/OxyPlot.AppVeyor.sln /property:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
#  - msbuild Source/OxyPlot.AppVeyor.sln /property:Platform=ARM /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  
after_build:
  - gitlink c:\projects\oxyplot -u https://github.com/oxyplot/oxyplot -f Source/OxyPlot.AppVeyor.sln -ignore Xwt,OxyPlot.Windows10,OxyPlot.MonoTouch,OxyPlot.Xamarin.Android,OxyPlot.Xamarin.iOS,OxyPlot.Xamarin.Forms.Platform.Android,OxyPlot.Xamarin.Forms.Platform.iOS,OxyPlot.Xamarin.Forms.Platform.iOS.Classic
  - NuGet pack Source\OxyPlot.Xwt\OxyPlot.Xwt.nuspec -version "%GitVersion_NuGetVersion%"

artifacts:
  - path: Output
    name: OxyPlot-Xwt-$(GitVersion_SemVer)
    type: zip
  - path: '*.nupkg'

deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: kM3Kse+ivuuE5RVoe6dPdw+aguWx56K2YeXujGa9tMPQTms3lv7QxNpTLFMALYNa
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/  
