platform: Any CPU
configuration: Release

pull_requests:
  do_not_increment_build_number: true

install:
  - cinst gitversion.portable --version=3.6.1 -y
  - cinst gitlink --version=2.3.0 -y

before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - git submodule update --init --recursive
  - NuGet restore Source/OxyPlot.AppVeyor.sln
  - gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: Source/OxyPlot.AppVeyor.sln
  verbosity: minimal
    
after_build:
  - gitlink c:\projects\oxyplot-xwt -u https://github.com/oxyplot/oxyplot-xwt -f Source/OxyPlot.AppVeyor.sln -ignore Xwt
  - NuGet pack Source\OxyPlot.Xwt\OxyPlot.Xwt.nuspec -version "%GitVersion_NuGetVersion%"

artifacts:
  - path: Output
    name: OxyPlot-Xwt-$(GitVersion_SemVer)
    type: zip
  - path: '*.nupkg'

deploy:
  provider: NuGet
  server: https://www.myget.org/F/oxyplot/api/v2/package
  api_key:
    secure: 2GnqgfpkOUH6Umfn1WWlun0b021+QeInBXkgQOQfa4/wDOYHLT757rrjTsb0lmon
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
